### ISSUE TITLE
Report software outputs in Pure

### ISSUE THREAD

**Issue by olexandr-konovalov** [ilnp/ilnp-public-1#2]
Please consider recording this software in Pure following the guidelines from https://code4ref.github.io/ (more specifically for Pure - https://code4ref.github.io/pure.html). This will allow us to have a better picture of all the variety of research software developed in St Andrews and get to know people behind it, and in its turn will help to campaign for the recognition of RSE roles at local and national (through https://rse.ac.uk/) levels.

**Comment by saleembhatti** [comment]
Done!

**Comment by olexandr-konovalov** [comment]
Thanks!
